# config.yaml
load_balancer:
  algorithm: "weighted_round_robin"

backends:
  - id: "backend-8001"
    url: "http://127.0.0.1:8001"
    weight: 2
    max_connections: 10000
  - id: "backend-8002"
    url: "http://127.0.0.1:8002"
    weight: 1
    max_connections: 10000
  - id: "backend-8003"
    url: "http://127.0.0.1:8003"
    weight: 1
    max_connections: 10000

health_check:
  interval_secs: 5
  timeout_secs: 2
  unhealthy_threshold: 3
  healthy_threshold: 2
  path: "/health"

circuit_breaker:
  failure_threshold: 5
  success_threshold: 2
  timeout_secs: 60

retry:
  max_attempts: 3
  backoff_base_ms: 100
  backoff_max_ms: 5000

metrics:
  enabled: true
  port: 9090
  path: "/metrics"